services:
  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    ports:
      - "5173:80"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    env_file:
      - server/.env
    ports:
      - "4000:4000"

