FROM node:20-bookworm-slim

RUN apt-get update && \
    apt-get install -y openssl && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY server/package*.json ./

RUN npm ci

COPY server/ ./

RUN npx prisma generate

EXPOSE 4000

CMD ["node", "src/server.js"]